---

- name: Update package repositories
  become: true
  apt:
    update_cache: True
  tags:
    - apt
    - update_cache

- name: Install cloudflare packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  register: install_cloudflare_package_dependencies
  with_items: "{{ _cloudflare_packages | default([]) }}"
  when: _cloudflare_packages is defined
  tags:
    - apt
    - dependencies
