---

- name: Update package repositories
  become: true
  apt:
    update_cache: True
  tags:
    - apt
    - update_cache

- name: Install cloudflare package dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  register: install_cloudflare_package_dependencies
  when: cloudflare_package_dependencies is defined
  with_items: cloudflare_package_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_cloudflare_package_dependencies.stdout_lines

- name: Install cloudflare dependencies
  become: true
  apt:
    name: "{{ item.name }}"
    state: present
  register: install_cloudflare_dependencies
  when: cloudflare_dependencies is defined
  with_items: cloudflare_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_cloudflare_dependencies.stdout_lines
