---
- name: Create files default
  sudo: yes
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    state: "{{ item.state }}"
  with_items: _cloudflare_create_files
  when: _cloudflare_create_files is defined

- name: Create files
  sudo: yes
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    state: "{{ item.state }}"
  with_items: cloudflare_create_files
  when: cloudflare_create_files is defined
