---

- name: copy templates
  template:
    src: "{{ item.src }}"
    owner: "{{ item.owner }}"
    mode: "{{ item.mode }}"
    dest: "{{ item.dest }}"
  with_items: _cloudflare.templates
  when: _cloudflare.templates is defined
